version: '3'
services:
  subway-db:
    image: library/mysql:5.7
    container_name: subway-db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: subway
      TZ: Asia/Seoul
    volumes:
      - ./data:/var/lib/mysql